# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/brian/privio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/brian/privio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brian/privio/CMakeFiles /home/brian/privio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brian/privio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bin/cmdhashes

# Build rule for target.
bin/cmdhashes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/cmdhashes
.PHONY : bin/cmdhashes

# fast build rule for target.
bin/cmdhashes/fast:
	$(MAKE) -f CMakeFiles/bin/cmdhashes.dir/build.make CMakeFiles/bin/cmdhashes.dir/build
.PHONY : bin/cmdhashes/fast

#=============================================================================
# Target rules for targets named bin/privio

# Build rule for target.
bin/privio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/privio
.PHONY : bin/privio

# fast build rule for target.
bin/privio/fast:
	$(MAKE) -f CMakeFiles/bin/privio.dir/build.make CMakeFiles/bin/privio.dir/build
.PHONY : bin/privio/fast

src/privio.o: src/privio.c.o
.PHONY : src/privio.o

# target to build an object file
src/privio.c.o:
	$(MAKE) -f CMakeFiles/bin/privio.dir/build.make CMakeFiles/bin/privio.dir/src/privio.c.o
.PHONY : src/privio.c.o

src/privio.i: src/privio.c.i
.PHONY : src/privio.i

# target to preprocess a source file
src/privio.c.i:
	$(MAKE) -f CMakeFiles/bin/privio.dir/build.make CMakeFiles/bin/privio.dir/src/privio.c.i
.PHONY : src/privio.c.i

src/privio.s: src/privio.c.s
.PHONY : src/privio.s

# target to generate assembly for a file
src/privio.c.s:
	$(MAKE) -f CMakeFiles/bin/privio.dir/build.make CMakeFiles/bin/privio.dir/src/privio.c.s
.PHONY : src/privio.c.s

src/privioUtil.o: src/privioUtil.c.o
.PHONY : src/privioUtil.o

# target to build an object file
src/privioUtil.c.o:
	$(MAKE) -f CMakeFiles/bin/cmdhashes.dir/build.make CMakeFiles/bin/cmdhashes.dir/src/privioUtil.c.o
	$(MAKE) -f CMakeFiles/bin/privio.dir/build.make CMakeFiles/bin/privio.dir/src/privioUtil.c.o
.PHONY : src/privioUtil.c.o

src/privioUtil.i: src/privioUtil.c.i
.PHONY : src/privioUtil.i

# target to preprocess a source file
src/privioUtil.c.i:
	$(MAKE) -f CMakeFiles/bin/cmdhashes.dir/build.make CMakeFiles/bin/cmdhashes.dir/src/privioUtil.c.i
	$(MAKE) -f CMakeFiles/bin/privio.dir/build.make CMakeFiles/bin/privio.dir/src/privioUtil.c.i
.PHONY : src/privioUtil.c.i

src/privioUtil.s: src/privioUtil.c.s
.PHONY : src/privioUtil.s

# target to generate assembly for a file
src/privioUtil.c.s:
	$(MAKE) -f CMakeFiles/bin/cmdhashes.dir/build.make CMakeFiles/bin/cmdhashes.dir/src/privioUtil.c.s
	$(MAKE) -f CMakeFiles/bin/privio.dir/build.make CMakeFiles/bin/privio.dir/src/privioUtil.c.s
.PHONY : src/privioUtil.c.s

util/cmdhashes.o: util/cmdhashes.c.o
.PHONY : util/cmdhashes.o

# target to build an object file
util/cmdhashes.c.o:
	$(MAKE) -f CMakeFiles/bin/cmdhashes.dir/build.make CMakeFiles/bin/cmdhashes.dir/util/cmdhashes.c.o
.PHONY : util/cmdhashes.c.o

util/cmdhashes.i: util/cmdhashes.c.i
.PHONY : util/cmdhashes.i

# target to preprocess a source file
util/cmdhashes.c.i:
	$(MAKE) -f CMakeFiles/bin/cmdhashes.dir/build.make CMakeFiles/bin/cmdhashes.dir/util/cmdhashes.c.i
.PHONY : util/cmdhashes.c.i

util/cmdhashes.s: util/cmdhashes.c.s
.PHONY : util/cmdhashes.s

# target to generate assembly for a file
util/cmdhashes.c.s:
	$(MAKE) -f CMakeFiles/bin/cmdhashes.dir/build.make CMakeFiles/bin/cmdhashes.dir/util/cmdhashes.c.s
.PHONY : util/cmdhashes.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... bin/cmdhashes"
	@echo "... bin/privio"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/privio.o"
	@echo "... src/privio.i"
	@echo "... src/privio.s"
	@echo "... src/privioUtil.o"
	@echo "... src/privioUtil.i"
	@echo "... src/privioUtil.s"
	@echo "... util/cmdhashes.o"
	@echo "... util/cmdhashes.i"
	@echo "... util/cmdhashes.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

